---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: ubuntu
    image:  geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
provisioner:
  name: ansible
  lint:
     name: ansible-lint
verifier:
  name: ansible
test_sequence:
        - lint
        - destroy
        - dependency
        - syntax
        - create
        - converge
#        - idempotence
        - verify
        - destroy
