---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  
  - name: Gather package facts
    package_facts:
        manager: auto

  - name: Get available groups
    getent:
        database: group

  - name: Check for group github
    debug:
        msg: "Group github exists."
    when: "'github' in ansible_facts.getent_group"

  - getent:
        database: passwd
        key: github
  - name: Get users/Check for user github
    debug:
        msg: "User github exists."
    when: "'github' in ansible_facts.getent_passwd"

  - name: Check home directory for github user exists
    stat:
        path: /home/github
    register: stat_result
  - debug:
        msg: "Home Directory for user github exists."
    when: stat_result.stat.exists


  - name: Check actions-runner directory for github user exists
    stat:
        path: /home/github/actions-runner
    register: stat_result_runner
  - debug:
        msg: "Actions-runner Directory for user github exists."
    when: stat_result_runner.stat.exists

  - name: Check if nvm is installed
    stat:
        path: /var/lib/nvm/nvm-exec
    register: stat_result_nvm
  - debug:
        msg: "nvm is installed."
    when: stat_result_nvm.stat.exists

  - name: Check if pyenv is installed
    stat:
        path: /home/github/.pyenv/bin/pyenv
    register: stat_result_pyenv
  - debug:
        msg: "pyenv is installed."
    when: stat_result_pyenv.stat.exists

  - name: Check if tfenv is installed
    stat:
        path: /root/bin/tfenv
    register: stat_result_tfenv
  - debug:
        msg: "tfenv is installed."
    when: stat_result_tfenv.stat.exists

  - name: Check if sdkman is installed
    stat:
        path: /root/.sdkman/bin/sdkman-init.sh
    register: stat_result_sdkman
  - debug:
        msg: "sdkman is installed."
    when: stat_result_sdkman.stat.exists
